/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReactionsRouteImport } from './routes/reactions'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PeriodicTableRouteImport } from './routes/periodic-table'
import { Route as MoleculesRouteImport } from './routes/molecules'
import { Route as LabRouteImport } from './routes/lab'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const ReactionsRoute = ReactionsRouteImport.update({
  id: '/reactions',
  path: '/reactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodicTableRoute = PeriodicTableRouteImport.update({
  id: '/periodic-table',
  path: '/periodic-table',
  getParentRoute: () => rootRouteImport,
} as any)
const MoleculesRoute = MoleculesRouteImport.update({
  id: '/molecules',
  path: '/molecules',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lab': typeof LabRoute
  '/molecules': typeof MoleculesRoute
  '/periodic-table': typeof PeriodicTableRoute
  '/progress': typeof ProgressRoute
  '/reactions': typeof ReactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lab': typeof LabRoute
  '/molecules': typeof MoleculesRoute
  '/periodic-table': typeof PeriodicTableRoute
  '/progress': typeof ProgressRoute
  '/reactions': typeof ReactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lab': typeof LabRoute
  '/molecules': typeof MoleculesRoute
  '/periodic-table': typeof PeriodicTableRoute
  '/progress': typeof ProgressRoute
  '/reactions': typeof ReactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/lab'
    | '/molecules'
    | '/periodic-table'
    | '/progress'
    | '/reactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/lab'
    | '/molecules'
    | '/periodic-table'
    | '/progress'
    | '/reactions'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/lab'
    | '/molecules'
    | '/periodic-table'
    | '/progress'
    | '/reactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LabRoute: typeof LabRoute
  MoleculesRoute: typeof MoleculesRoute
  PeriodicTableRoute: typeof PeriodicTableRoute
  ProgressRoute: typeof ProgressRoute
  ReactionsRoute: typeof ReactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reactions': {
      id: '/reactions'
      path: '/reactions'
      fullPath: '/reactions'
      preLoaderRoute: typeof ReactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/periodic-table': {
      id: '/periodic-table'
      path: '/periodic-table'
      fullPath: '/periodic-table'
      preLoaderRoute: typeof PeriodicTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/molecules': {
      id: '/molecules'
      path: '/molecules'
      fullPath: '/molecules'
      preLoaderRoute: typeof MoleculesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LabRoute: LabRoute,
  MoleculesRoute: MoleculesRoute,
  PeriodicTableRoute: PeriodicTableRoute,
  ProgressRoute: ProgressRoute,
  ReactionsRoute: ReactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
